### ISSUE TITLE
Upgrade 150 kHz ADCP (sn 15373) to hold four (4) batteries

### ISSUE THREAD

**Issue by neaptide** [nccoos/platforms#47]
Current status of Harvey's 150 kHz ADCP (sn 15373) is it has an **_external battery_** package that only holds two (2) battery packs.  We will need to purchase a larger tube that holds four (4) batteries. 

- [x] get quote  -- 12/6/2016 -- $9820.00
[RDI_Quotation_UNCCH-WHLEXTBC x 1_V1.pdf](https://github.com/nccoos/platforms/files/634390/RDI_Quotation_UNCCH-WHLEXTBC.x.1_V1.pdf)
- [x] determine source of funds to purchase
- [x] write sole source justification
- [x] get requisition since >$5k
- [x] place order

---------------------------------------
Trip said in an email dated June 6, 2016, "It's probably worth mentioning that your ADCP battery case only holds two batteries while ours hold four.  For a longer deployment time it would probably be required to get a larger battery tube (~$10k each)."

**Comment by muglia** [comment]
Does it make sense for me to actually purchase this added battery pack? I think running the sole source through UNC should be on your end, have it shipped here, and we'll equip. it for deployment, no?

**Comment by hseim** [comment]
Don’t think it matters too much, but if I need to do a sole source it is probably easier for me to initiate the purchase.  Do we have a quote?

H

**Comment by neaptide** [comment]
No quote.  Waiting on answers to the questions (revised for clarity) ...

**Comment by neaptide** [comment]
If I read the quote from TRDI, it looks like four (4) battery packs (WHABPLR) come with this purchase.

**Comment by hseim** [comment]
Excellent. Mike told me it may take a different style of battery than the smaller cases.

H

Sent from my iPhone

On Jan 13, 2017, at 13:41, Sara Haines <notifications@github.com<mailto:notifications@github.com>> wrote:


If I read the quote from TRDI, it looks like four (4) battery packs (WHABPLR) come with this purchase.

-

**Comment by muglia** [comment]
Great, and yes, we confirmed that it looks like the same battery packets with different mounting holes.
Mike

**Comment by neaptide** [comment]
Requisition has been approved and Elise is emailing purchasing agent to start order.

**Comment by neaptide** [comment]
PO sent Feb 9.  Expected ship date is Mar 1 2017 (Fedex Gnd) to Chapel Hill.  Will need to get it to CSI after we receive it.

**Comment by desimonenm** [comment]
Any update on the Battery pack shipment? I see it is suppose to be shipped on the 1st.  Has it been shipped and is there an estimated delivery date to Chapel Hill?  Knowing this would give me a better idea of what kind of time constraints I will have when installing the pack and calibrating the moorings.

**Comment by neaptide** [comment]
Received in Chapel Hill 20 min ago.  

Trying to figure out the logistics to get it from here to CSI.  Stand by ...
