### ISSUE TITLE
Freight Logistics to WHOI

### ISSUE THREAD

**Issue by neaptide** [nccoos/platforms#64]
Make arrangements to truck buoys, ADCP pods to WHOI by March 30, 2017.  This will require a full truck load (FTL) Step-down trailer.  The route is Morehead City, NC>Wanchese, NC>Woods Hole, MA.  Working with Rickie Meeks, owner of FlatbedShipping.com.  

- [x] Schedule dates for pickup, stop-over and delivery to arrive March 30.
- [x] Verify height to top of buoy ring (or highest point) when buoy is on side -- verified March 1, 2017 8.5 feet tall (102 inches).  
- [x] List all pieces, dimensions as loaded, weights
- [x] Layout of pieces
- [x] Get metal strapping tools and materials to secure anchor to pallet -- IMS has vynl strapping and tools
- [ ] ~~~Determine extra space available for additional pallet boxes~~~ -- not doing 
- [ ] ~~~Get shipping box from storage for delicate parts taken off buoys for transport~~~ -- not doing

### Finalized list for bill of lading

Number | Description | Weight (lbs) | Dimensions (feet, LxWxH) | Value
----------| -------------| -------------|-------------------|----------------
1 | Buoy (B1) | 2000 | 12'x7'x8.5' on side | $50,000
2 | Buoy (B2) | 2000 | 12'x7'x8.5' on side | $50,000
3 | Small Bottom Frame (B1) | 200 | 5'x5'x3' | $5,000
4 | Small Bottom Frame (B2) | 200 | 5'x5'x3' | $5,000
5 | Anchor Assembly | 2800 | 3’x’3’x3’ | $3,000
6 | Large Bottom Pod (A5) | 1200 | 5.6'x5.6'x3.5' | $121,000
7 | Large Bottom Pod (A6) | 1200 | 5.6'x5.6'x3.5' | $109,000
   |   |    |   |   
   |  |  TOTAL  |  9600  |  40'x7'x8.5'  |    $343,000

 Total weight not to exceed 12,000 lbs, but best estimate is 9600 lbs.  We have equipment and personnel to load and off-load at each location.  

Using [Stein Transportation Trailer Selection Guide](http://www.steintransportation.com/trailer-selector-guide.html) to help with dimensions of step down trailer capacity.

![buoys_on_truck_3](https://cloud.githubusercontent.com/assets/4511520/23169063/62352b4e-f818-11e6-9181-812d83f789c9.JPG)

**Comment by muglia** [comment]
I'd like to fill in the table, but not seeing how to do it so...
#6 A5 $120,703
#7 A6 $108.640 (less the hydrophone value)

**Comment by neaptide** [comment]
Shipment schedule finalized
Tues, March 28 at 8AM -- First pickup at IMS, Morehead City, NC (Stacy Davis)
Tues, March 28 at 3-4PM -- Second pickup at CSI in Wanchese, NC (Mike Muglia)
Thurs, March 30 by Noon or so -- Drop off at WHOI in Woods Hole, MA (Brian Hogue)
